version: '3'

services:
  zig:
    volumes:
      - "${ZIG_REPO_PATH}:/zig"
      - "${ZIG_BOOTSTRAP_REPO_PATH}:/zig-bootstrap"
    build:
      dockerfile: ./Dockerfile
      context: .
      network: "host"

